services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-easysmart
    restart: unless-stopped
    environment:
      POSTGRES_USER: easysmart
      POSTGRES_PASSWORD: easysmart123
      POSTGRES_DB: easysmart
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  easysmart-server:
    build:
      context: ../server
    container_name: easysmart-server
    restart: unless-stopped
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=easysmart
      - PG_PASSWORD=easysmart123
      - PG_DB=easysmart
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mqtt-broker

networks:
  default:
    name: easysmart-net
