services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-easysmart
    restart: unless-stopped
    environment:
      POSTGRES_USER: easysmart
      POSTGRES_PASSWORD: easysmart123
      POSTGRES_DB: easysmart
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  easysmart-server:
    build:
      context: ./server
    container_name: easysmart-server
    restart: unless-stopped
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: easysmart
      PG_PASSWORD: easysmart123
      PG_DB: easysmart
      MQTT_HOST: 172.17.0.1        # IP do host (onde roda o broker externo)
      MQTT_PORT: 1883
    ports:
      - "3000:3000"
    depends_on:
      - postgres

networks:
  default:
    name: easysmart-net
